title: Goader CLI
description: Công cụ tải và xử lý ảnh dành cho fan dịch.
remote_theme: just-the-docs/just-the-docs
search_enabled: true
color_scheme: dark
heading_anchors: true
aux_links:
  "Goader trên GitHub":
    - https://github.com/puleeno/goader
footer_content: "&copy; {{ site.time | date: '%Y' }} Goader CLI"

